name: Deploy Test Branch to GitHub Pages

on:
  push:
    branches:
      - InteligentPatches  # your testing branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build   # or your build command, e.g., jekyll build, hugo, etc.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # change to your build output folder
          destination_dir: test # this deploys to /test/ path
